"""
Earnings calendar export (RFC 5545 iCalendar / .ics).

Generates a single .ics file containing every NSE stock's next earnings
release as an all-day calendar event, with 24-hour and 1-hour reminders.
Users import the file once into Google Calendar (or any RFC-5545 client)
and the events appear on their calendar.

Sources and safety:
  - Earnings dates come from the same fundamentals feed used everywhere else
    (TradingView via tvkit), so they match the Next Earnings page exactly.
  - Only FUTURE dates (today or later, Nairobi time) are exported — past
    events are skipped. This matches the Next Earnings page rules.
  - Events are keyed by (symbol + date) so re-importing the file updates
    the existing event in place instead of duplicating it. Any calendar
    client that respects UID will merge cleanly.
  - Malformed dates and missing fields are simply skipped — the function
    never raises, so the pipeline is unaffected.

Nothing here is guessed: if a stock's earnings date isn't in the feed, no
event is produced for it.
"""

import os
from datetime import datetime, timedelta

from logger import get_logger

logger = get_logger(__name__)

CAL_NAME = "NSE Upcoming Earnings"
CAL_TZ = "Africa/Nairobi"


def _today_nairobi():
    try:
        from zoneinfo import ZoneInfo
        return datetime.now(ZoneInfo(CAL_TZ)).date()
    except Exception:
        return datetime.now().date()


def _escape(text: str) -> str:
    """Escape special characters for ICS text fields (RFC 5545 §3.3.11)."""
    if text is None:
        return ""
    return (str(text)
            .replace("\\", "\\\\")
            .replace(";", "\\;")
            .replace(",", "\\,")
            .replace("\n", "\\n"))


def build_ics(fundamentals_data: dict, source_label: str = "TradingView via kenyan-stock-analyzer") -> str:
    """
    Build the .ics content for every future earnings date in fundamentals_data.

    Returns the full ICS text (always at least a valid, empty VCALENDAR so
    the file is well-formed even when no earnings are on record).
    """
    today = _today_nairobi()
    dtstamp = datetime.utcnow().strftime("%Y%m%dT%H%M%SZ")

    events: list[tuple] = []  # (date, symbol, sector)
    for sym, f in (fundamentals_data or {}).items():
        if not f:
            continue
        raw = f.get("earnings_next_date")
        if not raw:
            continue
        try:
            edate = datetime.strptime(raw, "%Y-%m-%d").date()
        except (ValueError, TypeError):
            continue
        if edate < today:
            continue
        sector = f.get("sector") or ""
        events.append((edate, sym, sector))
    events.sort(key=lambda t: (t[0], t[1]))

    lines = [
        "BEGIN:VCALENDAR",
        "VERSION:2.0",
        f"PRODID:-//Kenyan Stock Analyzer//{CAL_NAME}//EN",
        "CALSCALE:GREGORIAN",
        "METHOD:PUBLISH",
        f"X-WR-CALNAME:{_escape(CAL_NAME)}",
        f"X-WR-TIMEZONE:{CAL_TZ}",
        f"X-WR-CALDESC:{_escape('Upcoming NSE earnings release dates. Auto-generated by kenyan-stock-analyzer. Source: ' + source_label)}",
    ]

    for edate, sym, sector in events:
        # All-day event: DTSTART (inclusive) and DTEND (exclusive, next day)
        dstart = edate.strftime("%Y%m%d")
        dend = (edate + timedelta(days=1)).strftime("%Y%m%d")
        # Stable UID so re-imports update the same event
        uid = f"{sym}-{dstart}@nse-earnings.kenyanstockanalyzer"
        summary = f"[NSE] {sym} — Earnings release"
        description = (
            f"Next earnings release for NSE:{sym}"
            + (f" ({sector})." if sector else ".")
            + f" Data source: {source_label}."
            + " Confirm the exact release time via the company's official NSE announcement."
        )
        lines += [
            "BEGIN:VEVENT",
            f"UID:{uid}",
            f"DTSTAMP:{dtstamp}",
            f"DTSTART;VALUE=DATE:{dstart}",
            f"DTEND;VALUE=DATE:{dend}",
            f"SUMMARY:{_escape(summary)}",
            f"DESCRIPTION:{_escape(description)}",
            f"CATEGORIES:NSE,Earnings,{_escape(sector) if sector else 'Kenya'}",
            "TRANSP:TRANSPARENT",  # doesn't block time — informational
            # 24-hour reminder
            "BEGIN:VALARM",
            "TRIGGER:-P1D",
            "ACTION:DISPLAY",
            f"DESCRIPTION:{_escape(sym)} earnings tomorrow",
            "END:VALARM",
            # 1-hour reminder
            "BEGIN:VALARM",
            "TRIGGER:-PT1H",
            "ACTION:DISPLAY",
            f"DESCRIPTION:{_escape(sym)} earnings in 1 hour",
            "END:VALARM",
            "END:VEVENT",
        ]

    lines.append("END:VCALENDAR")
    logger.info(f"Earnings calendar: {len(events)} future event(s) exported")
    # RFC 5545 requires CRLF line endings
    return "\r\n".join(lines) + "\r\n"


def write_ics(fundamentals_data: dict, output_path: str,
              source_label: str = "TradingView via kenyan-stock-analyzer") -> str | None:
    """
    Write the .ics file to disk. Returns the path on success, None on failure.
    Fails safe — the pipeline is unaffected by any error here.
    """
    try:
        content = build_ics(fundamentals_data, source_label=source_label)
        os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
        with open(output_path, "w", encoding="utf-8", newline="") as f:
            f.write(content)
        logger.info(f"Earnings calendar written: {output_path}")
        return output_path
    except Exception as e:
        logger.warning(f"Earnings calendar write failed: {e}")
        return None


# ---- Smoke test ----
if __name__ == "__main__":
    import json, glob
    from logger import setup_logging
    setup_logging()

    files = sorted(glob.glob("../data/fundamentals_*.json"))
    if not files:
        print("no fundamentals cache to test against")
    else:
        fund = json.load(open(files[-1]))
        ics = build_ics(fund)
        n_events = ics.count("BEGIN:VEVENT")
        print(f"generated ICS: {n_events} events, {len(ics)} bytes")
        # Sanity: is it well-formed?
        assert ics.startswith("BEGIN:VCALENDAR"), "bad prefix"
        assert ics.rstrip().endswith("END:VCALENDAR"), "bad suffix"
        assert "\r\n" in ics, "no CRLF"
        print("well-formed VCALENDAR ✓")
        # Dump first event
        first = ics.split("BEGIN:VEVENT")[1].split("END:VEVENT")[0]
        print("first event:", first[:400])
